services:
  app:
    environment:
      - DISPLAY=$DISPLAY
    container_name: alinka-linux
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "
        alembic upgrade head || exit 1
        && python run.py
      "

    volumes:
      - ".:/app/"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./documents:/home/qtuser/Alinka-dokumenty"
      - "./:/home/qtuser/.alinka"

    user: qtuser
