"""Add support_center table

Revision ID: 6660edaf8986
Revises: 7af3ac9f8735
Create Date: 2024-10-16 19:44:19.613866

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6660edaf8986"
down_revision: Union[str, None] = "7af3ac9f8735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_center",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("rspo", sa.Integer(), nullable=True),
        sa.Column("name_nominative", sa.String(length=1024), nullable=False),
        sa.Column("name_genetive", sa.String(length=1024), nullable=False),
        sa.Column("institute_name", sa.String(length=1024), nullable=False),
        sa.Column("kurator", sa.String(length=1024), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=False),
        sa.Column("town", sa.String(length=128), nullable=False),
        sa.Column("postal_code", sa.String(length=12), nullable=False),
        sa.Column("post", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_center")
    # ### end Alembic commands ###
