version: 0.2

env:
  variables:
    POETRY_VIRTUALENVS_CREATE: "false"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install poetry==1.4.0
      - poetry install --with dev --no-interaction -vvv

  build:
    commands:
      - echo $POETRY_VIRTUALENVS_CREATE
      - pytest .
      - black . --check
      - isort . --check
      - flake8 .
