version: 0.2

env:
  variables:
     DISPLAY: ""

phases:
  pre_build:
    commands:
      - make style-check
      - make test
      - export INSTALLER_FILE_NAME=`make installer-name`

  build:
    commands:
      - make installer

artifacts:
  files:
    - ${INSTALLER_FILE_NAME}
