name: Build develop packages
on:
  push:
    branches:
    - develop

jobs:
  build-deb:
    if: github.repository == 'CodeForPoznan/alinka-pyside'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build working docker image
      run: |
        make build
    - name: get application version
      # for unknown (yet?) reason setting APP_VERSION
      # before `make build` causes Github action to fail
      # with `make: docker: Argument list too long` error
      run : |
        APP_VERSION=$(docker compose run --rm app poetry version --short)-$(git rev-parse --short ${{ github.sha }})
        INSTALLER_FILE_NAME="alinka-${APP_VERSION}.deb"
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "INSTALLER_FILE_NAME=$INSTALLER_FILE_NAME" >> $GITHUB_ENV
    - name: build distribution package
      # we don't use currently Makefile here
      # as we want to inject git has as version
      # instead of relying on `poetry version`
      run: |
        docker compose run --rm -u root app pyinstaller alinka.spec --noconfirm
        docker compose run --rm -u root app ./package.sh
        docker compose run --rm -u root app fpm -v ${{ env.APP_VERSION }} -p ${{ env.INSTALLER_FILE_NAME }}
    - name: publish distribution package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.INSTALLER_FILE_NAME }}
        path: ${{ env.INSTALLER_FILE_NAME }}

  build-win:
    if: github.repository == 'CodeForPoznan/alinka-pyside'
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.9'
    - name: setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.1
        virtualenvs-create: true
    - name: install Python dependencies
      run: |
        poetry install --no-interaction --no-root --with dev
    - name: build PyInstaller package
      run: |
        poetry run pyinstaller alinka.spec --noconfirm
    - name: get application version
      run : |
        APP_VERSION=$(poetry version --short)-$(git rev-parse --short ${{ github.sha }})
        INSTALLER_FILE_NAME="Alinka-${APP_VERSION}.exe"
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "INSTALLER_FILE_NAME=$INSTALLER_FILE_NAME" >> $GITHUB_ENV
    - name: build distribution package
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: installer.iss
        options: /DAppVersion=${{ env.APP_VERSION }}
    - name: publish distribution package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.INSTALLER_FILE_NAME }}
        path: package/${{ env.INSTALLER_FILE_NAME }}
